version: '3.8'

services:
  golang-api:
    build:
      context: ./loadtest-go-api
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: itemsdb
      DB_PORT: 5432
    expose:
      - "3100"
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  nestjs-api:
    build:
      context: ./loadtest-nest-api
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      DB_HOST: postgres
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: itemsdb
      DB_PORT: 5432
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: itemsdb
    expose:
      - "5432"
